// Mock data for testing QuestionList components
import { Database } from './supabase'

type Question = Database['public']['Tables']['questions']['Row'] & {
  author: Database['public']['Tables']['users']['Row']
  category: Database['public']['Tables']['categories']['Row']
  _count: { count: number }
}

type Category = Database['public']['Tables']['categories']['Row']

export const mockCategories: Category[] = [
  {
    id: 1,
    name: '비자/법률',
    slug: 'visa',
    description: '비자 신청, 연장, 체류, 법률 문제 관련 질문',
    icon: '🛂',
    color: '#3B82F6',
    parent_id: null,
    sort_order: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 2,
    name: '취업/직장',
    slug: 'employment',
    description: '취업, 직장 생활, 근로 조건 관련 질문',
    icon: '💼',
    color: '#10B981',
    parent_id: null,
    sort_order: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 3,
    name: '주거/부동산',
    slug: 'housing',
    description: '집 구하기, 전월세, 주거 관련 질문',
    icon: '🏠',
    color: '#F59E0B',
    parent_id: null,
    sort_order: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 4,
    name: '의료/건강',
    slug: 'health',
    description: '의료보험, 병원, 건강 관련 질문',
    icon: '🏥',
    color: '#EF4444',
    parent_id: null,
    sort_order: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 5,
    name: '생활정보',
    slug: 'life',
    description: '일상 생활, 문화, 쇼핑, 교육 등 기타 정보',
    icon: '🌟',
    color: '#8B5CF6',
    parent_id: null,
    sort_order: 5,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
]

export const mockUsers = [
  {
    id: 'user-1',
    email: 'vietnam.student@example.com',
    name: '베트남학생',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vietnam1',
    bio: '한국에서 공부하는 베트남 학생입니다.',
    provider: 'google',
    provider_id: 'google-123',
    role: 'verified' as const,
    verification_status: 'approved' as const,
    verification_type: 'student' as const,
    specialty_areas: ['visa', 'education'],
    verified_at: '2024-01-15T00:00:00Z',
    verification_expires_at: null,
    visa_type: 'D-2',
    company: null,
    years_in_korea: 2,
    region: '서울',
    preferred_language: 'ko',
    is_verified: true,
    verification_date: '2024-01-15T00:00:00Z',
    trust_score: 75,
    badges: {
      senior: false,
      certified: false,
      verified: true,
      helper: true,
      moderator: false
    },
    question_count: 5,
    answer_count: 12,
    helpful_answer_count: 8,
    last_active: '2024-01-20T10:30:00Z',
    created_at: '2023-12-01T00:00:00Z',
    updated_at: '2024-01-20T10:30:00Z'
  },
  {
    id: 'user-2',
    email: 'hcm.resident@example.com',
    name: '호치민출신',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vietnam2',
    bio: '호치민에서 온 한국 거주자입니다.',
    provider: 'kakao',
    provider_id: 'kakao-456',
    role: 'verified' as const,
    verification_status: 'approved' as const,
    verification_type: 'resident' as const,
    specialty_areas: ['work', 'life'],
    verified_at: '2023-08-10T00:00:00Z',
    verification_expires_at: null,
    visa_type: 'F-2',
    company: '한국기업',
    years_in_korea: 5,
    region: '부산',
    preferred_language: 'ko',
    is_verified: true,
    verification_date: '2023-08-10T00:00:00Z',
    trust_score: 92,
    badges: {
      senior: true,
      certified: false,
      verified: true,
      helper: true,
      moderator: false
    },
    question_count: 3,
    answer_count: 28,
    helpful_answer_count: 22,
    last_active: '2024-01-19T15:20:00Z',
    created_at: '2023-06-15T00:00:00Z',
    updated_at: '2024-01-19T15:20:00Z'
  }
]

export const mockQuestions: Question[] = [
  {
    id: '1',
    title: '한국에서 비자 연장 신청 방법이 궁금합니다',
    content: '학생비자(D-2)에서 취업비자(E-7)로 변경하려고 하는데 필요한 서류와 절차를 알고 싶습니다. 특히 어떤 회사 서류가 필요한지, 소요 기간은 얼마나 되는지 궁금합니다.',
    author_id: 'user-1',
    category_id: 1,
    tags: ['비자연장', 'D-2', 'E-7', '취업비자'],
    ai_category_confidence: 0.95,
    ai_tags: ['visa', 'employment', 'documents'],
    urgency: 'high',
    matched_certified_users: ['visa-certified-1', 'employment-certified-2'],
    certified_notifications_sent: true,
    view_count: 127,
    answer_count: 3,
    helpful_count: 2,
    upvote_count: 8,
    downvote_count: 1,
    status: 'open',
    is_pinned: false,
    is_featured: false,
    is_reported: false,
    is_approved: true,
    moderated_by: null,
    moderated_at: null,
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-15T10:30:00Z',
    last_activity_at: '2024-01-18T14:20:00Z',
    resolved_at: null,
    search_vector: null,
    author: mockUsers[0],
    category: mockCategories[0],
    _count: { count: 3 }
  },
  {
    id: '2',
    title: '서울에서 베트남 음식 재료 구매할 수 있는 곳',
    content: '베트남 요리를 해먹고 싶은데 어디서 재료를 구할 수 있을까요? 특히 쌀국수, 피시소스, 베트남 고수 등을 찾고 있습니다.',
    author_id: 'user-2',
    category_id: 3,
    tags: ['베트남음식', '재료구매', '서울', '쇼핑'],
    ai_category_confidence: 0.88,
    ai_tags: ['food', 'shopping', 'vietnamese'],
    urgency: 'normal',
    matched_certified_users: ['food-certified-1'],
    certified_notifications_sent: false,
    view_count: 89,
    answer_count: 5,
    helpful_count: 4,
    upvote_count: 12,
    downvote_count: 0,
    status: 'resolved',
    is_pinned: true,
    is_featured: false,
    is_reported: false,
    is_approved: true,
    moderated_by: null,
    moderated_at: null,
    created_at: '2024-01-14T15:20:00Z',
    updated_at: '2024-01-16T09:45:00Z',
    last_activity_at: '2024-01-16T09:45:00Z',
    resolved_at: '2024-01-16T09:45:00Z',
    search_vector: null,
    author: mockUsers[1],
    category: mockCategories[2],
    _count: { count: 5 }
  },
  {
    id: '3',
    title: '한국 회사에서 일할 때 주의사항',
    content: '한국 회사 문화와 업무 방식에 대해 조언 부탁드립니다. 특히 상하관계, 회식 문화, 업무 소통 방식 등이 궁금합니다.',
    author_id: 'user-1',
    category_id: 2,
    tags: ['회사문화', '업무', '소통', '조언'],
    ai_category_confidence: 0.92,
    ai_tags: ['work', 'culture', 'communication'],
    urgency: 'normal',
    matched_certified_users: ['culture-certified-1', 'work-certified-2'],
    certified_notifications_sent: true,
    view_count: 203,
    answer_count: 7,
    helpful_count: 6,
    upvote_count: 15,
    downvote_count: 2,
    status: 'open',
    is_pinned: false,
    is_featured: true,
    is_reported: false,
    is_approved: true,
    moderated_by: null,
    moderated_at: null,
    created_at: '2024-01-13T09:45:00Z',
    updated_at: '2024-01-19T16:30:00Z',
    last_activity_at: '2024-01-19T16:30:00Z',
    resolved_at: null,
    search_vector: null,
    author: mockUsers[0],
    category: mockCategories[1],
    _count: { count: 7 }
  }
]